# Generated by Django 3.0.7 on 2020-11-25 21:50

from django.db import migrations
from django.db import IntegrityError, transaction
from django.utils.timezone import now
from ..models import Security
from ..utils_valute import get_valute_code

def create_custom_valute(apps, schema_editor):
    valute = ['EUR','USD']
    for i in valute:
        try:
            with transaction.atomic():
                Security.objects.create(
                    name=i+'RUB',
                    fullname=i,
                    shortname=i,
                    regnumber=i,
                    secid=i,
                    isin=i,
                    code=get_valute_code(i),
                    security_type='currency',
                    last_update=now().date(),
                    oldest_date=now().date()
                )
        except Exception as e:
            print(i)
            print(e)
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0032_auto_20201125_2219'),
    ]

    operations = [
        migrations.RunPython(create_custom_valute),
    ]
